stages:
  - ci

angular_ci:
  stage: ci
  image: node:20

  rules:
    # ExÃ©cute le job si le frontend change
    - changes:
        - Web/**/*
        - .gitlab-ci.yml
      when: always
    - when: never

  before_script:
    - cd Web

  script:
    - echo "ğŸ“¦ Installation des dÃ©pendances"
    - npm install
